FROM maven:3.8.4-jdk-8 AS build

WORKDIR /build
COPY mvnw ./
COPY pom.xml ./
COPY .mvn ./

RUN mvn -B dependency:go-offline
COPY src ./src
RUN mvn -B package -DskipTests

FROM openjdk:8-jdk-alpine
WORKDIR /serv
RUN apk add --no-cache bash
COPY --from=build /build/target/*.jar app.jar
COPY wait-for-it.sh ./
RUN chmod +x wait-for-it.sh
EXPOSE 8087
CMD ["./wait-for-it.sh", "-t", "30", "session-service:8081", "--", \
    "./wait-for-it.sh", "-t", "30", "hotel-service:8082", "--", \
    "./wait-for-it.sh", "-t", "30", "booking-service:8083", "--", \
    "./wait-for-it.sh", "-t", "30", "payment-service:8084", "--", \
    "./wait-for-it.sh", "-t", "30", "loyalty-service:8085", "--", \
    "./wait-for-it.sh", "-t", "30", "report-service:8086", "--", \
     "java", "-jar", "app.jar"]